# Generated by Django 5.2 on 2025-05-19 10:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profilemodel",
            name="image",
            field=models.ImageField(
                default="profile/default.jpeg",
                upload_to="profile",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        ["jpg", "png", "jpeg", "webp"]
                    )
                ],
            ),
        ),
    ]
