# Generated by Django 5.0.6 on 2024-10-02 10:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="postmodel",
            options={"ordering": ["-date_created"]},
        ),
    ]
