# Generated by Django 5.2 on 2025-05-19 10:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0003_postmodel_likes_comment"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="postmodel",
            options={},
        ),
        migrations.RemoveField(
            model_name="postmodel",
            name="likes",
        ),
        migrations.AlterField(
            model_name="postmodel",
            name="title",
            field=models.CharField(max_length=255),
        ),
        migrations.DeleteModel(
            name="Comment",
        ),
    ]
